config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  get 'welcome/:first_name', to: 'index#show'
  get 'static_pages/team'
  get 'static_pages/contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :new, :create]
  resources :gossips, only: [:index,:show, :new, :create, :edit, :update, :destroy]
  resources :cities, only: [:show]
  resources :sessions, only: [:destroy, :create, :new]
  resources :comments, only: [:show, :create, :edit, :destroy, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, presence: true
  validates :zip_code, 
    presence: true, 
    format: { with: /\d{5}(?:[-\s]\d{4})?/ } #https://stackoverflow.com/a/2577239
  has_many :users
  has_many :gossips
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip

  validates :content, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, 
    presence: true, 
    length: { in: 3..14 }
  validates :content, presence: true
  belongs_to :user
  belongs_to :city
  has_many :join_table_tag_gossips
  has_many :tags, through: :join_table_tag_gossips
  has_many :comments
end

app/models/join_table_tag_gossip.rb
class JoinTableTagGossip < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  validates :recipient_id, presence: true
  validates :sender_id, presence: true
  
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :title, 
    presence: true, 
    length: { in: 3..14 }
  has_many :join_table_tag_gossips
  has_many :gossips, through: :join_table_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
  before_save {  |user| user.email = email.downcase }
  validates :first_name, 
    presence: true, 
    length: { in: 2..14 }
  validates :last_name, 
    presence: true, 
    length: { in: 2..14 }
  validates :email, 
    presence: true, 
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  validates :age, 
    presence: true, 
    length: { maximum: 3} #format: { with: /^\d{3}$/ }
  validates :description, 
    presence: true, 
    length: { maximum: 500 }
  validates :password, 
    presence: true,
    length: { minimum: 6 }
  validates :password_confirmation, presence: true

  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :comments
  has_secure_password
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :authenticate_user

  def show
    @cities = City.all
    @city = City.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user
  include CommentHelper

  def create
    puts params
    @comment = Comment.new(gossip_id: params[:gossip_id], user_id: session[:user_id], content: params[:content])
    if @comment.save      # si ça marche, le comment est save et le user est redirigé vers la même page avec un message success
      redirect_to gossip_path(params[:gossip_id])
    else                  # sinon, refresh de la page avec un message d'erreur
      flash[:danger] = 'Quelques chose ne va pas.'
      redirect_to gossip_path(params[:gossip_id])
      flash.delete(:danger)
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params) &&  User.find_by(id: session[:user_id]).id == params[:id] 
      redirect_to @gossip
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if who_i_am(params[:id])
      @comment.destroy
    end
    redirect_to gossips_path
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, except: [:index]

  def index
    puts "$" * 60
    puts "Voici le message de l'URL :"
    puts  params[:first_name]
    puts "$" * 60
    @first_name = params[:first_name]
    @gossips = Gossip.all
  end

  def show
    puts "$" * 60
    puts params[:id]
    puts "$" * 60
    @gossip = Gossip.find(params[:id])
    @comment = Comment.new
    @gossip_comments = Gossip.find(params[:id]).comments
  end

  def new
    @gossip = Gossip.new

  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def create
    id = session[:user_id]
    @user = User.find(id)
    puts title:params[:title]
    @gossip = Gossip.new(user_id: @user.id, city_id: @user.city_id, title:params[:title], content:params[:content])
    if @gossip.save
    puts 'redirect'
    flash[:success] = "Bravo, ton potin a été enregistré"
    redirect_to @gossip
    else
    puts "doesn't work"
    render :new
    end
  end

  def update
    @gossip = Gossip.find(params[:id])
    puts who_i_am(params[:id])
    if @gossip.update(gossip_params) && who_i_am(params[:id]) 

      redirect_to @gossip
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    if who_i_am(params[:id])  
    @gossip.destroy
    end
    redirect_to gossips_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
     # cherche s'il existe un utilisateur en base avec l’e-mail
    user = User.find_by(email:params[:email])
    puts params[:email]
    puts params[:password]
    puts user.first_name

     # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe 
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      # redirige où tu veux, avec un flash ou pas
      flash[:success] = "#{user.first_name} log in"
      redirect_to root_path

    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(description: Faker::TvShows::SiliconValley.quote, city_id: City.all.sample.id, first_name:params[:first_name], last_name:params[:last_name], email:params[:email], age: Faker::Number.between(1, 100), password:params[:password], password_confirmation:params[:password_confirmation])
    if @user.save
      redirect_to(root_path)
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
  def who_i_am(user_id)
    if User.find_by(id: session[:user_id]).id == user_id
      puts "1111111111111111111111111111111111111111111111111ZZZZZZ"
      return true
    end
    puts "333333333333333333333333333333333333"
    return false
  end
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    return User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?(user)
    if user == nil
    else
      current_user
    end
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

<!-- Latest compiled and minified CSS -->
<title>TheGossipProjectNewPg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <header>
  
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand"  style="color: #ff00ff" href="/">The Gossip Project</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" > <%= link_to "Home ", root_path %> <span class="sr-only">(current)</span> &nbsp</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"> <%= link_to "Dream Team ", static_pages_team_path %> &nbsp</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"> <%= link_to "Contact ", static_pages_contact_path %> &nbsp</a>
        </li>
        <li class="nav-item">
          <% if User.find_by(id: session[:user_id]) %>
            <li class="nav-item">
            <a class="nav-link"><%= link_to "Log out", session_path(session[:user_id]), method: :delete %>&nbsp</a>
            </li>
          <% elsif %>
            <li class="nav-item">
            <a class="nav-link" ><%= link_to "Sign in", new_session_path %>&nbsp</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" ><%= link_to "Sign up", new_user_path %>&nbsp</a>
            </li>
          </div>
          <% end %>
        </li>

      </ul>
    </div>
  </div>
  </nav>
  

  </header>
  <body>
    <%= yield %>

  </body>
</html>